/*
 Navicat Premium Data Transfer

 Source Server         : local postgre
 Source Server Type    : PostgreSQL
 Source Server Version : 160004 (160004)
 Source Host           : localhost:5433
 Source Catalog        : BangXepHangDB
 Source Schema         : public

 Target Server Type    : PostgreSQL
 Target Server Version : 160004 (160004)
 File Encoding         : 65001

 Date: 05/09/2025 15:44:01
*/


-- ----------------------------
-- Sequence structure for Customers_Id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."Customers_Id_seq";
CREATE SEQUENCE "public"."Customers_Id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for GameScores_Id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."GameScores_Id_seq";
CREATE SEQUENCE "public"."GameScores_Id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1;

-- ----------------------------
-- Table structure for Customers
-- ----------------------------
DROP TABLE IF EXISTS "public"."Customers";
CREATE TABLE "public"."Customers" (
  "Id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1
),
  "Name" varchar(100) COLLATE "pg_catalog"."default" NOT NULL,
  "Avatar" varchar(500) COLLATE "pg_catalog"."default",
  "CreatedAt" timestamptz(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
)
;

-- ----------------------------
-- Records of Customers
-- ----------------------------
INSERT INTO "public"."Customers" VALUES (1, 'Nguyễn Văn An', 'https://example.com/avatar1.jpg', '2025-09-05 15:15:09.981923+07');
INSERT INTO "public"."Customers" VALUES (2, 'Trần Thị Bình', 'https://example.com/avatar2.jpg', '2025-09-05 15:15:09.981923+07');
INSERT INTO "public"."Customers" VALUES (3, 'Lê Văn Cường', 'https://example.com/avatar3.jpg', '2025-09-05 15:15:09.981923+07');
INSERT INTO "public"."Customers" VALUES (4, 'Phạm Thị Dung', 'https://example.com/avatar4.jpg', '2025-09-05 15:15:09.981923+07');
INSERT INTO "public"."Customers" VALUES (5, 'Hoàng Văn Em', 'https://example.com/avatar5.jpg', '2025-09-05 15:15:09.981923+07');
INSERT INTO "public"."Customers" VALUES (6, 'Vũ Thị Phương', 'https://example.com/avatar6.jpg', '2025-09-05 15:15:09.981923+07');
INSERT INTO "public"."Customers" VALUES (7, 'Đặng Văn Giang', 'https://example.com/avatar7.jpg', '2025-09-05 15:15:09.981923+07');
INSERT INTO "public"."Customers" VALUES (8, 'Bùi Thị Hoa', 'https://example.com/avatar8.jpg', '2025-09-05 15:15:09.981923+07');
INSERT INTO "public"."Customers" VALUES (9, 'Phan Văn Inh', 'https://example.com/avatar9.jpg', '2025-09-05 15:15:09.981923+07');
INSERT INTO "public"."Customers" VALUES (10, 'Võ Thị Khoa', 'https://example.com/avatar10.jpg', '2025-09-05 15:15:09.981923+07');

-- ----------------------------
-- Table structure for GameScores
-- ----------------------------
DROP TABLE IF EXISTS "public"."GameScores";
CREATE TABLE "public"."GameScores" (
  "Id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1
),
  "CustomerId" int4 NOT NULL,
  "PlayTime" timestamptz(6) NOT NULL,
  "Score" int4 NOT NULL,
  "CreatedAt" timestamptz(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
)
;

-- ----------------------------
-- Records of GameScores
-- ----------------------------
INSERT INTO "public"."GameScores" VALUES (1, 1, '2024-01-05 10:30:00+07', 1200, '2025-09-05 15:15:09.984107+07');
INSERT INTO "public"."GameScores" VALUES (2, 1, '2024-01-10 14:20:00+07', 1500, '2025-09-05 15:15:09.984107+07');
INSERT INTO "public"."GameScores" VALUES (3, 1, '2024-01-15 09:15:00+07', 1800, '2025-09-05 15:15:09.984107+07');
INSERT INTO "public"."GameScores" VALUES (4, 1, '2024-01-20 16:45:00+07', 2100, '2025-09-05 15:15:09.984107+07');
INSERT INTO "public"."GameScores" VALUES (5, 1, '2024-01-25 11:30:00+07', 1900, '2025-09-05 15:15:09.984107+07');
INSERT INTO "public"."GameScores" VALUES (6, 2, '2024-01-03 08:45:00+07', 1000, '2025-09-05 15:15:09.984107+07');
INSERT INTO "public"."GameScores" VALUES (7, 2, '2024-01-08 13:20:00+07', 1300, '2025-09-05 15:15:09.984107+07');
INSERT INTO "public"."GameScores" VALUES (8, 2, '2024-01-12 15:10:00+07', 1600, '2025-09-05 15:15:09.984107+07');
INSERT INTO "public"."GameScores" VALUES (9, 2, '2024-01-18 10:25:00+07', 1400, '2025-09-05 15:15:09.984107+07');
INSERT INTO "public"."GameScores" VALUES (10, 2, '2024-01-22 17:30:00+07', 1700, '2025-09-05 15:15:09.984107+07');
INSERT INTO "public"."GameScores" VALUES (11, 3, '2024-01-02 12:00:00+07', 1100, '2025-09-05 15:15:09.984107+07');
INSERT INTO "public"."GameScores" VALUES (12, 3, '2024-01-07 14:30:00+07', 1400, '2025-09-05 15:15:09.984107+07');
INSERT INTO "public"."GameScores" VALUES (13, 3, '2024-01-14 09:45:00+07', 1700, '2025-09-05 15:15:09.984107+07');
INSERT INTO "public"."GameScores" VALUES (14, 3, '2024-01-19 16:15:00+07', 2000, '2025-09-05 15:15:09.984107+07');
INSERT INTO "public"."GameScores" VALUES (15, 3, '2024-01-24 11:20:00+07', 1800, '2025-09-05 15:15:09.984107+07');
INSERT INTO "public"."GameScores" VALUES (16, 4, '2024-01-04 09:30:00+07', 900, '2025-09-05 15:15:09.984107+07');
INSERT INTO "public"."GameScores" VALUES (17, 4, '2024-01-09 15:45:00+07', 1200, '2025-09-05 15:15:09.984107+07');
INSERT INTO "public"."GameScores" VALUES (18, 4, '2024-01-16 08:20:00+07', 1500, '2025-09-05 15:15:09.984107+07');
INSERT INTO "public"."GameScores" VALUES (19, 4, '2024-01-21 13:10:00+07', 1300, '2025-09-05 15:15:09.984107+07');
INSERT INTO "public"."GameScores" VALUES (20, 4, '2024-01-26 16:40:00+07', 1600, '2025-09-05 15:15:09.984107+07');
INSERT INTO "public"."GameScores" VALUES (21, 5, '2024-01-01 11:15:00+07', 800, '2025-09-05 15:15:09.984107+07');
INSERT INTO "public"."GameScores" VALUES (22, 5, '2024-01-06 14:50:00+07', 1100, '2025-09-05 15:15:09.984107+07');
INSERT INTO "public"."GameScores" VALUES (23, 5, '2024-01-11 10:35:00+07', 1300, '2025-09-05 15:15:09.984107+07');
INSERT INTO "public"."GameScores" VALUES (24, 5, '2024-01-17 15:25:00+07', 1200, '2025-09-05 15:15:09.984107+07');
INSERT INTO "public"."GameScores" VALUES (25, 5, '2024-01-23 12:40:00+07', 1400, '2025-09-05 15:15:09.984107+07');
INSERT INTO "public"."GameScores" VALUES (26, 6, '2024-01-13 08:10:00+07', 1000, '2025-09-05 15:15:09.984107+07');
INSERT INTO "public"."GameScores" VALUES (27, 6, '2024-01-28 14:20:00+07', 1300, '2025-09-05 15:15:09.984107+07');
INSERT INTO "public"."GameScores" VALUES (28, 7, '2024-01-06 16:30:00+07', 1200, '2025-09-05 15:15:09.984107+07');
INSERT INTO "public"."GameScores" VALUES (29, 7, '2024-01-13 11:45:00+07', 1500, '2025-09-05 15:15:09.984107+07');
INSERT INTO "public"."GameScores" VALUES (30, 7, '2024-01-20 09:20:00+07', 1800, '2025-09-05 15:15:09.984107+07');
INSERT INTO "public"."GameScores" VALUES (31, 7, '2024-01-27 15:10:00+07', 1600, '2025-09-05 15:15:09.984107+07');
INSERT INTO "public"."GameScores" VALUES (32, 8, '2024-01-11 12:15:00+07', 1100, '2025-09-05 15:15:09.984107+07');
INSERT INTO "public"."GameScores" VALUES (33, 8, '2024-01-18 16:30:00+07', 1400, '2025-09-05 15:15:09.984107+07');
INSERT INTO "public"."GameScores" VALUES (34, 8, '2024-01-25 10:45:00+07', 1700, '2025-09-05 15:15:09.984107+07');
INSERT INTO "public"."GameScores" VALUES (35, 9, '2024-01-08 09:40:00+07', 900, '2025-09-05 15:15:09.984107+07');
INSERT INTO "public"."GameScores" VALUES (36, 9, '2024-01-15 13:25:00+07', 1200, '2025-09-05 15:15:09.984107+07');
INSERT INTO "public"."GameScores" VALUES (37, 9, '2024-01-22 11:50:00+07', 1500, '2025-09-05 15:15:09.984107+07');
INSERT INTO "public"."GameScores" VALUES (38, 9, '2024-01-29 14:35:00+07', 1300, '2025-09-05 15:15:09.984107+07');
INSERT INTO "public"."GameScores" VALUES (39, 10, '2024-01-12 10:20:00+07', 1000, '2025-09-05 15:15:09.984107+07');
INSERT INTO "public"."GameScores" VALUES (40, 10, '2024-01-19 15:15:00+07', 1300, '2025-09-05 15:15:09.984107+07');
INSERT INTO "public"."GameScores" VALUES (41, 10, '2024-01-26 08:30:00+07', 1600, '2025-09-05 15:15:09.984107+07');
INSERT INTO "public"."GameScores" VALUES (42, 1, '2024-02-05 10:30:00+07', 2000, '2025-09-05 15:15:09.991144+07');
INSERT INTO "public"."GameScores" VALUES (43, 1, '2024-02-10 14:20:00+07', 2200, '2025-09-05 15:15:09.991144+07');
INSERT INTO "public"."GameScores" VALUES (44, 2, '2024-02-08 13:20:00+07', 1800, '2025-09-05 15:15:09.991144+07');
INSERT INTO "public"."GameScores" VALUES (45, 2, '2024-02-15 15:10:00+07', 2000, '2025-09-05 15:15:09.991144+07');
INSERT INTO "public"."GameScores" VALUES (46, 3, '2024-02-12 14:30:00+07', 1900, '2025-09-05 15:15:09.991144+07');
INSERT INTO "public"."GameScores" VALUES (47, 3, '2024-02-18 09:45:00+07', 2100, '2025-09-05 15:15:09.991144+07');
INSERT INTO "public"."GameScores" VALUES (48, 4, '2024-02-14 15:45:00+07', 1700, '2025-09-05 15:15:09.991144+07');
INSERT INTO "public"."GameScores" VALUES (49, 5, '2024-02-20 11:15:00+07', 1600, '2025-09-05 15:15:09.991144+07');
INSERT INTO "public"."GameScores" VALUES (50, 6, '2024-02-25 08:10:00+07', 1500, '2025-09-05 15:15:09.991144+07');
INSERT INTO "public"."GameScores" VALUES (51, 7, '2024-02-22 16:30:00+07', 1900, '2025-09-05 15:15:09.991144+07');

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."Customers_Id_seq"
OWNED BY "public"."Customers"."Id";
SELECT setval('"public"."Customers_Id_seq"', 10, true);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."GameScores_Id_seq"
OWNED BY "public"."GameScores"."Id";
SELECT setval('"public"."GameScores_Id_seq"', 51, true);

-- ----------------------------
-- Auto increment value for Customers
-- ----------------------------
SELECT setval('"public"."Customers_Id_seq"', 10, true);

-- ----------------------------
-- Primary Key structure for table Customers
-- ----------------------------
ALTER TABLE "public"."Customers" ADD CONSTRAINT "PK_Customers" PRIMARY KEY ("Id");

-- ----------------------------
-- Auto increment value for GameScores
-- ----------------------------
SELECT setval('"public"."GameScores_Id_seq"', 51, true);

-- ----------------------------
-- Indexes structure for table GameScores
-- ----------------------------
CREATE INDEX "IX_GameScores_CustomerId_PlayTime" ON "public"."GameScores" USING btree (
  "CustomerId" "pg_catalog"."int4_ops" ASC NULLS LAST,
  "PlayTime" "pg_catalog"."timestamptz_ops" ASC NULLS LAST
);
CREATE INDEX "IX_GameScores_PlayTime" ON "public"."GameScores" USING btree (
  "PlayTime" "pg_catalog"."timestamptz_ops" ASC NULLS LAST
);

-- ----------------------------
-- Primary Key structure for table GameScores
-- ----------------------------
ALTER TABLE "public"."GameScores" ADD CONSTRAINT "PK_GameScores" PRIMARY KEY ("Id");

-- ----------------------------
-- Foreign Keys structure for table GameScores
-- ----------------------------
ALTER TABLE "public"."GameScores" ADD CONSTRAINT "FK_GameScores_Customers_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES "public"."Customers" ("Id") ON DELETE CASCADE ON UPDATE NO ACTION;
